
[Character - Alien]

card "/starwars/Virtual13-Dark/t_aemongremmwithpercussivecannon" "�Aemon Gremm With Percussive Cannon (2)\nDark Character - Alien [C]\nSet: Virtual Set 13\nPower: 3 Ability: 2\nDeploy: 3 Forfeit: 4\nIcons: Warrior, Permanent weapon\n\nLore: Crimson Dawn. Hylobon guard leader.\n\nText: Permanent weapon is Percussive Cannon (may target a character or vehicle for free; draw destiny; if destiny > defense value, target hit and is power and forfeit -2). While with your guard or at an opponent's site, opponent's weapon destiny draws here are -1."
card "/starwars/Virtual13-Dark/t_drydenvos" "�Dryden Vos (1)\nDark Character - Alien [C]\nSet: Virtual Set 13\nPower: 4 Ability: 3\nDeploy: 6 Forfeit: 6\nIcons: Pilot, Warrior\n\nLore: Crimson Dawn leader. Gangster.\n\nText: Deploys -2 if Maul on table. When deployed, may deploy a weapon on Vos from Reserve Deck; reshuffle. While armed and present at a site, opponent may not 'react' to or from here. Immune to attrition < 5 (< 3 if with Qi'ra)."
card "/starwars/Virtual13-Dark/t_hylobonenforcer" "��Hylobon Enforcer (3)\nDark Character - Alien [C]\nSet: Virtual Set 13\nPower: 3 Ability: 2\nDeploy: 4 Forfeit: 4\nIcons: Warrior, Permanent weapon\n\nLore: Crimson Dawn. Hylobon guard.\n\nText: Deploy -1 and forfeit +1 at same or related location as Vos or at an opponent's site. Permanent weapon is Percussive Cannon (may target a character using 1 Force; draw destiny; if destiny +1 > defense value, target's game text is canceled for remainder of turn)."
card "/starwars/Virtual13-Dark/t_margo" "�Margo (2)\nDark Character - Alien [C]\nSet: Virtual Set 13\nPower: 2 Ability: 2\nDeploy: 2 Forfeit: 3\nIcons: \n\nLore: Female Imroosian. Crimson Dawn.\n\nText: Once during opponent's deploy phase, may use 1 Force to choose: 'break cover' of opponent's Undercover spy here or draw destiny; if destiny = number of opponent's characters at same site, to initiate battle here this turn requires +1 Force."

[Character - Dark Jedi Master]

card "/starwars/Virtual13-Dark/t_darthtyranus" "�Darth Tyranus (1)\nDark Character - Dark Jedi Master [C]\nSet: Virtual Set 13\nPower: 5 Ability: 7\nDeploy: 7 Forfeit: 8\nIcons: Pilot, Warrior, Separatist, Episode I\n\nLore: Serennian leader. Trade Federation.\n\nText: Deploys -1 to an [Episode I] location. Jedi here are power and immunity to attrition -1. During battle or lightsaber combat involving Dooku, may cancel and redraw an opponent's just drawn destiny. Immune to Sorry About The Mess and attrition < 6."

[Character - Droid]

card "/starwars/Virtual13-Dark/t_id9probedroid" "���ID9 Probe Droid (3)\nDark Character - Droid [C]\nSet: Virtual Set 13\nPower: 1 Ability: \nDeploy: 1 Forfeit: 4\nIcons: \n\nLore: Spy.\n\nText: During your deploy phase, may use 2 Force to relocate an Inquisitor to same site and place this droid in Used Pile. While present with Seventh Sister, opponent may not target Seventh Sister with weapons unless this card 'hit.'"

[Character - Imperial]

card "/starwars/Virtual13-Dark/t_admiralozzel" "�Admiral Ozzel (V) (0)\nDark Character - Imperial [R1]\nSet: Virtual Set 13\nPower: 2 Ability: 2\nDeploy: 2 Forfeit: 4\nIcons: Pilot\n\nLore: Leader of the Emperor's Death Squadron assigned to hunt down and crush the Rebellion. As clumsy as he is stupid. Has just failed Darth Vader for the next-to-last time.\n\nText: Adds 2 to power of anything he pilots. Matching pilot for any Death Squadron Star Destroyer and, while piloting one, instead of Force draining here, may draw top card of Reserve Deck or raise your same or related converted location to the top."
card "/starwars/Virtual13-Dark/t_eighthbrother" "�Eighth Brother (3)\nDark Character - Imperial [C]\nSet: Virtual Set 13\nPower: 3 Ability: 5\nDeploy: 4 Forfeit: 5\nIcons: Pilot, Warrior\n\nLore: Terrelian Jango Jumper. Inquisitor.\n\nText: Adds 2 to power of anything he pilots. May deploy or move as a 'react' to same site as a 'Hatred' card. During your move phase, unless alone, may return one of your Inquisitors here (and all cards on them) to owner's hand."
card "/starwars/Virtual13-Dark/t_fifthbrother" "�Fifth Brother (2)\nDark Character - Imperial [C]\nSet: Virtual Set 13\nPower: 4 Ability: 5\nDeploy: 4 Forfeit: 6\nIcons: Pilot, Warrior\n\nLore: Inquisitor.\n\nText: Power +3 and defense value -2 while with a Jedi, Padawan, or 'Hatred' card. Characters here may not have their forfeit increased."
card "/starwars/Virtual13-Dark/t_ninthsister" "�Ninth Sister (2)\nDark Character - Imperial [C]\nSet: Virtual Set 13\nPower: 5 Ability: 5\nDeploy: 4 Forfeit: 4\nIcons: Pilot, Warrior\n\nLore: Female Dowutin Inquisitor.\n\nText: Defense value -2 while opponent has a weapon present. While at a site, unless opponent's character of ability > 3 here, reset opponent's total battle destiny here to 0."
card "/starwars/Virtual13-Dark/t_seventhsister" "�Seventh Sister (2)\nDark Character - Imperial [C]\nSet: Virtual Set 13\nPower: 4 Ability: 5\nDeploy: 5 Forfeit: 7\nIcons: Pilot, Warrior\n\nLore: Female Mirialan Inquisitor.\n\nText: Attrition against you is -1 here while with a Jedi, Padawan, probe droid, or 'Hatred' card. Once per turn, may use 1 Force (free if your probe droid here) to draw top card of Reserve Deck. Your Inquisitors and probe droids here are immune to attrition < 4."

[Character - Sith]

card "/starwars/Virtual13-Dark/t_maul" "�Maul (0.5)\nDark Character - Sith [C]\nSet: Virtual Set 13\nPower: 4 Ability: 6\nDeploy: 4 Forfeit: 8\nIcons: Warrior\n\nLore: Crimson Dawn leader. Gangster.\n\nText: Never deploys to a battleground. Opponent may not cancel your destiny draws. Once per turn, may add 1 to a just drawn battle or weapon destiny. Once per turn, may subtract 1 from a just drawn battle or weapon destiny. Immune to attrition < 5."

[Defensive Shield]

card "//starwars/Virtual13-Dark/t_failureatthecave" "�Failure At The Cave (V) (0)\nDark Defensive Shield [R]\nSet: Virtual Set 13\n\nLore: 'That place is strong with the dark side of the Force. A domain of evil it is. In you must go.'\n\nText: Plays on table. Opponent's Undercover spies are immune to Double Agent. While a Jedi Test on table, Projection Of A Skywalker is canceled. If Grimtaash just revealed your hand, you may place up to two cards from hand in your Used Pile."
card "/starwars/Virtual13-Dark/t_planetaryrings" "Planetary Rings (4)\nDark Effect [C]\nSet: Virtual Set 13\n\nLore: 'We're gonna get pulverized if we stay out here much longer.'\n\nText: Deploy on a battleground planet system. Adds one [Light Side] icon at your related Big One. If a sector was just drawn for asteroid destiny, cancel and redraw that destiny. Once per turn, may deploy a sector to this system from Reserve Deck; reshuffle. [Immune to Alter.]"
card "/starwars/Virtual13-Dark/t_therearemanyhuntingyounow" "�There Are Many Hunting You Now (4)\nDark Effect [C]\nSet: Virtual Set 13\n\nLore: Blank\n\nText: Deploy on table. Once during your turn, may stack top card of Lost Pile face down (as a 'Hatred' card) on an opponent's character with your Inquisitor. Opponent must choose to lose 1 Force or that character's game text is canceled for remainder of turn. [Immune to Alter.]"
card "/starwars/Virtual13-Dark/t_visageoftheemperor" "�Visage Of The Emperor (V) (7)\nDark Effect [R]\nSet: Virtual Set 13\n\nLore: Palpatine's hologram. Imposing. Ominous. Intimidating. Instrument for the evil Emperor's sinister reach across the galaxy. Used on a secret frequency of the Imperial HoloNet.\n\nText: Lose 2 Force to deploy on Vader's Castle. Your Force generation here may not be limited. Each player loses 1 Force at the end of their own turn. Once per game, may take a lightsaber into hand from Reserve Deck; reshuffle. [Immune to Alter]."

[Interrupt - Lost]

card "/starwars/Virtual13-Dark/t_workingmuchmoreclosely" "�Working Much More Closely (3)\nDark Interrupt - Lost [R]\nSet: Virtual Set 13\n\nLore: Hologram.\n\nText: If you have two Crimson Dawn characters in battle together, draw destiny and subtract that amount from attrition against you. OR Deploy up to two Crimson Dawn characters from Reserve Deck; reshuffle. OR Cancel a hologram."

[Interrupt - Used]

card "/starwars/Virtual13-Dark/t_alawlesstime" "�A Lawless Time (4)\nDark Interrupt - Used [R]\nSet: Virtual Set 13\n\nLore: Blank\n\nText: Lose 2 Force to retrieve a Crimson Dawn leader. OR If you just fired a [Set 13] blaster during a battle, add one battle destiny. OR During any control phase, if Maul or Vos at a battleground site, flip Shadow Collective (or You Know Who I Answer To)."
card "/starwars/Virtual13-Dark/t_imperialcodecylinder" "Imperial Code Cylinder (V) (4)\nDark Interrupt - Used [C2]\nSet: Virtual Set 13\n\nLore: Imperial officers are issued coded cylinders which access computer information via Scomp links. Each cylinder is coded to the officer's own security clearance.\n\nText: Take Krennic or a non-spy captain into hand from Reserve Deck; reshuffle. OR Peek at the bottom card of any deck or pile. OR During the power segment of a battle, if your captain in battle with your leader, cancel one destiny just drawn (except a battle destiny)."

[Interrupt - Used or Lost]

card "/starwars/Virtual13-Dark/t_farmorefrighteningthandeath" "�Far More Frightening Than Death (4)\nDark Interrupt - Used or Lost [R]\nSet: Virtual Set 13\n\nLore: Blank\n\nText: USED: Stack top card of Lost Pile face down (as a 'Hatred' card) on opponent's leader (or character of ability > 3) at a battleground. LOST: If your Inquisitor in battle with a Jedi, Padawan, or 'Hatred' card, add one battle destiny (add two if with all three)."
card "/starwars/Virtual13-Dark/t_ineveraskforanythingtwice" "�I Never Ask For Anything Twice (4)\nDark Interrupt - Used or Lost [R]\nSet: Virtual Set 13\n\nLore: Blank\n\nText: USED: Take First Light or Vos into hand from Reserve Deck; reshuffle. OR Place a character from hand in Used Pile to activate 1 Force (2 if Vos on table). LOST: Once per game, exchange two cards in hand with any one card in Lost Pile. [Immune to Sense.]"
card "/starwars/Virtual13-Dark/t_ivebeensearchingforyouforsometime" "I’ve Been Searching For You For Some Time (5)\nDark Interrupt - Used or Lost [R]\nSet: Virtual Set 13\n\nLore: Blank\n\nText: USED: If opponent's character is about to be lost, place all 'Hatred' cards (if any) on that character in owner's Used Pile. LOST: Lose Vader or an Inquisitor from hand to take up to two Inquisitors into hand from Reserve Deck; reshuffle."

[Location - Site]

card "/starwars/Virtual13-Dark/t_dathomirmaulschambers" "�Dathomir: Maul’s Chambers (0)\nDark Location - Site [U2]\nSet: Virtual Set 13\nIcons: Interior, Planet, Scomp Link\n\nText:\n{TODO: EDIT GAME TEXT}DARK (2): May deploy [Set 13] Maul here from Reserve Deck; reshuffle.  LIGHT (0): Jar Jar and your spies (except Ezra) may not deploy here. Opponent may not Force drain here."
card "/starwars/Virtual13-Dark/t_executorcontrolstation" "*�Executor: Control Station (0)\nDark Location - Site [U]\nSet: Virtual Set 13\nIcons: Interior, Mobile, Starship, Scomp Link\n\nText:\n{TODO: EDIT GAME TEXT}DARK (2): While your Imperial here, [Dagobah] Executor is deploy -7 (except to Fondor).  LIGHT (0): Force drain -1 here. If you initiate battle here, add one battle destiny."
card "/starwars/Virtual13-Dark/t_firstlightbar" "�First Light: Bar (0)\nDark Location - Site [U2]\nSet: Virtual Set 13\nIcons: Interior, Mobile, Starship, Scomp Link\n\nText:\n{TODO: EDIT GAME TEXT}DARK (2): Once per game, may deploy Margo, Wuher, or a musician here from Reserve Deck; reshuffle.  LIGHT (1): Force drain -1 here (if your musician here, Force drain +1 instead)."
card "/starwars/Virtual13-Dark/t_firstlightdrydensstudy" "�First Light: Dryden’s Study (0)\nDark Location - Site [U2]\nSet: Virtual Set 13\nIcons: Interior, Mobile, Starship, Scomp Link\n\nText:\n{TODO: EDIT GAME TEXT}DARK (2): During your move phase, your Crimson Dawn leader may move between here and a site.  LIGHT (0): Add 1 to your blaster weapon destiny draws here. Unless Vos on table, Force drain -1 here."
card "/starwars/Virtual13-Dark/t_firstlightreceptionarea" "�First Light: Reception Area (0)\nDark Location - Site [U2]\nSet: Virtual Set 13\nIcons: Interior, Mobile, Starship, Scomp Link\n\nText:\n{TODO: EDIT GAME TEXT}DARK (2): While your unique (•) alien here, your Force generation is +1 here (+2 if Margo).  LIGHT (1): Force drain -1 here (if your smuggler here, Force drain +1 instead)."
card "/starwars/Virtual13-Dark/t_malachorsithtempleentrance" "�Malachor: Sith Temple Entrance (0)\nDark Location - Site [U2]\nSet: Virtual Set 13\nIcons: Underground, Interior, Exterior, Planet\n\nText:\n{TODO: EDIT GAME TEXT}DARK (2): You initiate battles here for free. Unless you occupy, Inquisitors deploy -1 here.  LIGHT (1): Once per game, you may deploy a Padawan (except Anakin) here from Reserve Deck; reshuffle."
card "/starwars/Virtual13-Dark/t_malachorsithtempleupperchamber" "�Malachor: Sith Temple Upper Chamber (0)\nDark Location - Site [U2]\nSet: Virtual Set 13\nIcons: Underground, Interior, Planet\n\nText:\n{TODO: EDIT GAME TEXT}DARK (2): Force drain +1 here. While Vader alone here, he is power +2.  LIGHT (1): While Ahsoka alone (or with Ezra) here, she is power +2."

[Location - System]

card "/starwars/Virtual13-Dark/t_wakeelmui" "*�Wakeelmui (V) (0)\nDark Location - System [U]\nSet: Virtual Set 13\nIcons: Planet\n\nText:\n{TODO: EDIT GAME TEXT}DARK (2): Your TIEs may deploy here as a 'react.'  LIGHT (1): While opponent has more starships here than you, your starships here are power -1."

[Objective]

card "/TWOSIDED/starwars/Virtual13-Dark/t_huntdownanddestroythejedi" "Hunt Down And Destroy The Jedi / Their Fire Has Gone Out Of The Universe (V) (0/7)\nDark Objective [R]\nSet: Virtual Set 13\nIcons: \n{TODO: EDIT GAME TEXT}Hunt Down And Destroy The Jedi: Deploy Vader's Castle and [Set 13] Visage Of The Emperor. {For} remainder of game, you may not deploy characters except bounty hunters, droids, and Imperials. Where you have an Inquisitor, your total battle destiny is +1 (+2 if with a 'Hatred' card). Inquisitors are destiny +2. {While} this side up, once per turn, may deploy a [Cloud City] or Malachor battleground site from Reserve Deck; reshuffle. {Flip} this card if Vader is at a battleground site unless Luke, a Jedi, or a Padawan at a battleground site. Their Fire Has Gone Out Of The Universe: {While} this side up, you lose no Force from Visage Of The Emperor. While Vader armed with a lightsaber, opponent's Force drain bonuses are canceled. {Flip} this card if Luke, a Jedi, or a Padawan at a battleground site; once per game, may take Vader and your cards on him into hand from a site you control."
card "/TWOSIDED/starwars/Virtual13-Dark/t_shadowcollective" "Shadow Collective / You Know Who I Answer To (0/7)\nDark Objective [C]\nSet: Virtual Set 13\nIcons: \n{TODO: EDIT GAME TEXT}Shadow Collective: Deploy Maul's Chambers. If Massassi Throne Room on table, may deploy [Set 13] Maul to Maul's Chambers. {For} remainder of game, you may not deploy cards with ability (or [Episode I] droids) except characters with 'Black Sun,' 'Crimson Dawn,' or 'Hutt' in lore, assassins, gangsters, [Episode I] bounty hunters, and [Independent] starships. Once per turn, may deploy a non-unique blaster (or a card with 'First Light' in title) from Reserve Deck; reshuffle. {Flip} this card if you just 'hit' a character (or during your battle phase if your gangsters control two battlegrounds). You Know Who I Answer To: {May immediately} re-circulate and shuffle your Reserve Deck. {While} this side up, if your gangster leader in battle at same site as your non-unique blaster, may add one destiny to total power. During your draw phase, if Maul alone, may peek at the cards in your Force Pile. {Flip} this card at end of turn. If you are about to flip this card and you occupy three battlegrounds, opponent loses 1 Force."

[Weapon - Character]

card "/starwars/Virtual13-Dark/t_blacksunblaster" "Black Sun Blaster (4)\nDark Weapon - Character [C]\nSet: Virtual Set 13\n\nLore: Highly specialized weapon used for disintegration. Commonly found on the black market and in criminal arsenals. One of the favored weapons of the Black Sun.\n\nText: Use 1 Force to deploy on your alien warrior (free if your Black Sun agent leader on table). May target a character or vehicle for free. Draw destiny. If destiny +1 > defense value, target hit and you may activate 1 Force."
card "/starwars/Virtual13-Dark/t_crimsondawnblaster" "���Crimson Dawn Blaster (3)\nDark Weapon - Character [C]\nSet: Virtual Set 13\n\nLore: Blank\n\nText: Use 1 Force to deploy on your warrior (free if your Crimson Dawn leader on table). May target a character or vehicle for free. Draw destiny. If destiny +1 > defense value, target hit and may not be used to satisfy attrition."
