
[Character - Alien]

card "/starwars/Virtual13-Light/t_captainlandocalrissian" "�Captain Lando Calrissian (3)\nLight Character - Alien [C]\nSet: Virtual Set 13\nPower: 2 Ability: 3\nDeploy: 2 Forfeit: 4\nIcons: Pilot, Warrior\n\nLore: Smuggler and gambler.\n\nText: Adds 2 to power of anything he pilots. If a battle was just initiated here, may exchange a card in hand with an Interrupt of destiny = 4 from Reserve Deck; reshuffle. Once per game, if you have completed a Kessel Run, may return Lando to hand."
card "/starwars/Virtual13-Light/t_hansolo" "�Han… Solo (1)\nLight Character - Alien [C]\nSet: Virtual Set 13\nPower: 3 Ability: 3\nDeploy: 2 Forfeit: 5\nIcons: Pilot, Warrior\n\nLore: Corellian gambler, smuggler, and thief.\n\nText: Adds 2 to power and maneuver of anything he pilots or drives. If exactly one 'coaxium' card here, may take it into hand. While piloting Falcon and you have completed a Kessel Run, adds one battle destiny and opponent generates no Force here."
card "/starwars/Virtual13-Light/t_qira" "�Qi’ra (2)\nLight Character - Alien [C]\nSet: Virtual Set 13\nPower: 3 Ability: 4\nDeploy: 3 Forfeit: 3\nIcons: Pilot, Warrior\n\nLore: Female thief. Corellian smuggler.\n\nText: When forfeited at same location as Han or Vos, may satisfy all remaining battle damage against you. If you just initiated a battle or Force drain at same battleground and you have completed a Kessel Run, opponent loses 1 Force. Immune to attrition < 3."
card "/starwars/Virtual13-Light/t_riodurant" "�Rio Durant (4)\nLight Character - Alien [C]\nSet: Virtual Set 13\nPower: 3 Ability: 2\nDeploy: 3 Forfeit: 4\nIcons: Pilot, Warrior x2\n\nLore: Ardennian smuggler and thief.\n\nText: Adds 2 to power of anything he pilots. Once per turn, if you just deployed a smuggler here, may place a card from hand in Used Pile to activate 2 Force. Once per game, if you just won a battle here, may steal a starfighter from opponent's Lost Pile into hand."
card "/starwars/Virtual13-Light/t_tobiasbeckett" "�Tobias Beckett (0)\nLight Character - Alien [C]\nSet: Virtual Set 13\nPower: 4 Ability: 3\nDeploy: 3 Forfeit: 5\nIcons: Warrior\n\nLore: Glee Anselmian smuggler. Information broker, musician, and thief.\n\nText: If Vos or a [Set 13] smuggler on table, destiny +3 when drawn for destiny. Cancels Aurra's game text here. If just lost, may place out of play (for remainder of game, Han adds one battle destiny). If opponent just initiated a battle here, Beckett may fire a blaster."
card "/starwars/Virtual13-Light/t_val" "�Val (2)\nLight Character - Alien [C]\nSet: Virtual Set 13\nPower: 2 Ability: 2\nDeploy: 2 Forfeit: 4\nIcons: Warrior, Permanent weapon\n\nLore: Female scout, smuggler, and thief.\n\nText: May forfeit in place of your 'hit' [Set 13] smuggler here, restoring that smuggler to normal. Permanent weapon is Blaster Pistol (may target a character or creature for free; draw destiny; target hit, and its forfeit = 0, if destiny +1 > defense value)."

[Character - Alien/Rebel]

card "/starwars/Virtual13-Light/t_chewbacca" "�Chewbacca (V) (1)\nLight Character - Alien/Rebel [R2]\nSet: Virtual Set 13\nPower: 7 Ability: 2\nDeploy: 4 Forfeit: 6\nIcons: Pilot, Warrior\n\nLore: Wookiee smuggler from Kashyyyk. Over 200 years old. Top-notch mechanic and pilot. Jabba has large bounty on this 'walking carpet.' Friends call him Chewie...or Fuzzball.\n\nText: Adds 2 to power of anything he pilots (3 if Falcon). May deploy -1 as a 'react' (-2 to same location as Han). If you have completed a Kessel Run, opponent's Force retrieval is canceled. During battle here (or at a holosite), your dejariks are destiny +2."

[Character - Droid]

card "/starwars/Virtual13-Light/t_l337" "�L3-37 (Elthree-Threeseven) (3)\nLight Character - Droid [C]\nSet: Virtual Set 13\nPower: 2 Ability: \nDeploy: 2 Forfeit: 4\nIcons: Pilot, Astromech\n\nLore: Female smuggler.\n\nText: While aboard (or stacked on) a freighter, adds 1 to power, maneuver, and hyperspeed, and when forfeiting L3-37, stack her on that freighter. May lose L3-37 to cancel a non-[Immune to Sense] Interrupt targeting a freighter she is aboard or stacked on."

[Character - Jedi Master]

card "/starwars/Virtual13-Light/t_quigonjinnserenejedi" "�Qui-Gon Jinn, Serene Jedi (1)\nLight Character - Jedi Master [C]\nSet: Virtual Set 13\nPower: 6 Ability: 7\nDeploy: 6 Forfeit: 8\nIcons: Warrior, Episode I\n\nLore: Qui-Gon's sense of control assisted him in his final confrontation with Darth Maul. The ability to heal oneself in battle, mentally and physically, can be a huge advantage.\n\nText: Once per game, may deploy Meditation on Qui-Gon from Lost Pile. If alone during battle: your total battle destiny is +1 for each weapon destiny draw that was completed while alone this battle, and opponent may not cancel your destiny draws. Immune to attrition."
card "/starwars/Virtual13-Light/t_yodamasteroftheforce" "�Yoda, Master Of The Force (V) (4)\nLight Character - Jedi Master [PM]\nSet: Virtual Set 13\nPower: 3 Ability: 7\nDeploy: 4 Forfeit: 7\nIcons: Episode I\n\nLore: Jedi Council Member. 'More to say have you?'\n\nText: Power +3 while defending a battle (or while exactly two Jedi on table). Once per game, during your move phase, may relocate to a battleground site as a regular move. Immune to attrition."

[Defensive Shield]

card "//starwars/Virtual13-Light/t_clumsyandstupid" "�Clumsy And Stupid (0)\nLight Defensive Shield [R]\nSet: Virtual Set 13\n\nLore: 'Lord Vader, the fleet has moved out of lightspeed and we're preparing to aah . . . ukh . . . uh . . . uuuuukkk!'\n\nText: Plays on table. Opponent's Undercover spies are immune to Nevar Yalnal. Field Promotion is canceled if on Ozzel or opponent's [Maintenance] card. If Monnok just revealed your hand, you may place up to two cards from hand in your Used Pile."
card "/starwars/Virtual13-Light/t_kesselrun" "�Kessel Run (V) (5)\nLight Effect [R2]\nSet: Virtual Set 13\n\nLore: Planet Kessel has infamous glitterstim spice mines attracting smugglers and pirates. A 'Kessel run' is a long, dangerous hyper-route they must travel quickly.\n\nText: Deploy on Kessel; draw 'coaxium' destinies, stacking face up here until total > 12 (cannot deploy otherwise). During each move phase, if your smuggler here, move a 'coaxium' card from here to Used Pile. If no 'coaxium' cards here, retrieve 4 Force; place Effect out of play."
card "/starwars/Virtual13-Light/t_meditation" "�Meditation (V) (4)\nLight Effect [R]\nSet: Virtual Set 13\n\nLore: To prepare for the inevitable conflict with Jabba's minions, Luke entered a calm state of mental preparation.\n\nText: Deploy on your character of ability > 3. Opponent's aliens here are power -1 (and forfeit -2 if a leader, [Maintenance], or [Permanent Weapon] card). During battle at same site, if opponent has more characters participating than you, may add one battle destiny (then lose Effect at end of battle)."
card "/starwars/Virtual13-Light/t_twilightisuponme" "Twilight Is Upon Me (V) (5)\nLight Effect [R]\nSet: Virtual Set 13\n\nLore: When a Jedi dies, the spirit spreads through the Force and touches the living.\n\nText: If He Is The Chosen One on table, deploy on table. You may not deploy [Episode I] sites. While Luke with Prophecy Of The Force, your Force generation is +1 and opponent's Force generation is -1. May deploy Yoda's Hut from Reserve Deck; reshuffle. [Immune to Alter.]"

[Interrupt - Used]

card "/starwars/Virtual13-Light/t_hansdice" "Han's Dice (3)\nLight Interrupt - Used [C2]\nSet: Virtual Set 13\n\nLore: A pair of dice dangling above Millennium Falcon's cockpit, for luck. 'I've never seen anything to make me believe there's one, all-powerful Force controlling everything.'\n\nText: If Han or your gambler is in battle (with no Jedi), draw destiny: (0-2) subtract that amount from opponent's total battle destiny; (3-4) cancel the game text of a character participating in battle (if any); (5+) opponent loses all immunity to attrition (if any) this battle."
card "/starwars/Virtual13-Light/t_ivegotareallygoodfeelingaboutthis" "�I’ve Got A Really Good Feeling About This (4)\nLight Interrupt - Used [R]\nSet: Virtual Set 13\n\nLore: Blank\n\nText: If you have two smugglers on table, choose one: If opponent has more cards in hand than you, draw one card from Reserve Deck (two if [Set 13] Han on table). OR If there are more [Dark Side] than [Light Side] on table, activate 1 Force (2 if [Set 13] Han on table). OR Re-circulate."
card "/starwars/Virtual13-Light/t_savareenstandoff" "�Savareen Standoff (3)\nLight Interrupt - Used [R]\nSet: Virtual Set 13\n\nLore: Blank\n\nText: If a battle was just initiated, immediately fire a blaster deployed on your smuggler present. That blaster may fire again this battle. OR Your smuggler armed with a weapon card is defense value +2 for remainder of turn (even if just targeted by an Interrupt or weapon)."

[Interrupt - Used or Lost]

card "/starwars/Virtual13-Light/t_anakinskywalker" "�Anakin Skywalker (4)\nLight Interrupt - Used or Lost [R]\nSet: Virtual Set 13\n\nLore: 'You were right about me. Tell your sister ... you were right.'\n\nText: If I Feel The Conflict on table: USED: Take a Death Star II site into hand from Reserve Deck; reshuffle. OR Relocate Prophecy Of The Force to a site. LOST: During battle at a site, if Luke armed with [Death Star II] Luke's Lightsaber, choose: Add one destiny to attrition. OR Cancel the game text of a character of ability < 4."
card "/starwars/Virtual13-Light/t_hesthebestsmuggleraround" "�He’s The Best Smuggler Around (4)\nLight Interrupt - Used or Lost [C]\nSet: Virtual Set 13\n\nLore: Blank\n\nText: USED: Take Kessel Run, L3-37, or Lando into hand from Reserve Deck; reshuffle. OR If you just moved a 'coaxium' card to Used Pile, randomly retrieve 1 Force. LOST: Once per game, place a card stacked on [Set D] A Useless Gesture in your Lost Pile."
card "/starwars/Virtual13-Light/t_helpmeobiwankenobiquiteamercenary" "Help Me Obi-Wan Kenobi & Quite A Mercenary (4)\nLight Interrupt - Used or Lost [R]\nSet: Virtual Set 13\n\nLore: Blank\n\nText: If opponent's Audience Chamber on table, opponent loses 1 Force when you play this Interrupt. USED: Cancel Elis Helrot or Stunning Leader. [Immune to Sense.] OR Cancel a smuggler's game text for remainder of turn. LOST: During your move phase, 'break cover' of an Undercover spy. OR During battle, target an opponent's character of ability < 2 with your Jedi or smuggler; target is excluded from battle."

[Location - Site]

card "/starwars/Virtual13-Light/t_deathstariichasmwalkway" "�Death Star II: Chasm Walkway (0)\nLight Location - Site [C]\nSet: Virtual Set 13\nIcons: Interior, Mobile, Scomp Link, Death Star II\n\nText:\n{TODO: EDIT GAME TEXT}LIGHT (2): While Luke alone here, he is power +2.  DARK (2): Your total power here is -1 for each card stacked on I Feel The Conflict."

[Location - System]

card "/starwars/Virtual13-Light/t_corellia" "*�Corellia (0)\nLight Location - System [R1]\nSet: Virtual Set 13\nIcons: Planet\n\nText:\n{TODO: EDIT GAME TEXT}LIGHT (2): Your Corellians and freighters deploy -1 here. Your starships are hyperspeed +1 when moving to or from here.  DARK (1): If This Place Can Be A Little Rough on table, Force drain -1 here."
card "/starwars/Virtual13-Light/t_kessel" "*�Kessel (0)\nLight Location - System [U2]\nSet: Virtual Set 13\nIcons: Planet\n\nText:\n{TODO: EDIT GAME TEXT}LIGHT (1): For remainder of game, while you occupy Kessel, Force drain +1 there and Kessel Run may not be canceled.  DARK (2): If you control, Kessel Run is prevented (canceled)."

[Starship - Capital: Resistance Transport]

card "/starwars/Virtual13-Light/t_leiasresistancetransport" "Leia’s Resistance Transport (3)\nLight Starship - Capital: Resistance Transport [U]\nSet: Virtual Set 13\nPower: 3 Armor: 4 Hyperspeed: 3\nDeploy: 3 Forfeit: 5\nIcons: Pilot, Nav Computer, Scomp Link, Resistace\n\nLore: Blank\n\nText: May add 2 pilots and 5 passengers. Permanent pilot provides ability of 2. Deploys and moves like a starfighter. When deployed, may deploy a female Resistance character aboard for free from Reserve Deck; reshuffle."

[Weapon - Character]

card "/starwars/Virtual13-Light/t_rock" "Rock (5)\nLight Weapon - Character [C]\nSet: Virtual Set 13\n\nLore: Blank\n\nText: Ewok weapon. Deploy on your warrior or Ewok. May 'throw' (place in Used Pile) to target a character. For remainder of turn, target is power -3 (and if Proxima, she cannot battle). If on a Corellian and a battle just initiated at same site, may 'throw' Rock."
